### ISSUE TITLE
Validar opções da votação para somente permitir as disponíveis

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/votacao-rapida#40]

**Comment by thiagogomesverissimo** [comment]
Para reproduzir, basta inspecionar o formulário de votação com o chrome e trocar o value, e simplesmente é aceito. 
```
<div class="form-check space">
<input type="radio" class="form-check-input" name="alternativa_id" **value="1721"** id="check_1721"> 
<label class="form-check-label" for="check_1721">Contrário</label>
</div>
```

**Comment by thiagogomesverissimo** [comment]
No cálculo dos resultados também ignorar respostas que por ventura entrarem com opções não disponíveis. Acredito que o mesmo problema ocorra caso o pessoal do apoio altere as opções de respostas depois de uma votação já encerrada.

**Comment by masakik** [comment]
acho que no calculo dos resultados não precisaria não é? É necessário validar quando os dados vem do usuário. Uma vez computado o voto, aceitamos que estão corretos.
