### ISSUE TITLE
limitar apelido a 20 caracteres

### ISSUE THREAD

**Issue by zuqueto** [uspdev/votacao-rapida#42]
Limitar o apelido a 20 caracteres para ficar melhor na hora da exibição dos resultados

**Comment by masakik** [comment]
Legal isso.

**Comment by masakik** [comment]
Limitando também o tamanho de outros campos no form para instruir o usuário mas não impedindo injection. De qualquer forma essas ações são logadas no sistema e o injection pode ser rastreado.
