### ISSUE TITLE
Adição dos modelos SGBD

### ISSUE THREAD

**Issue by igorvc** [uspdev/votacao-rapida#52]
Olá, boa tarde:

Realizei o checkout do projeto, porém não foi possível instanciar a aplicação por falta dos modelos do SGBD.

Assim, por favor, poderia disponibilizar?

Abraço,

**Comment by igorvc** [comment]
Bem, atualizando, após configurar o .env, verifiquei que existem alguns arquivos dentro da pasta /cli.

Assim, executei o "inicalizar_bd.php" e alguams tabelas foram criadas:

php inicalizar_bd.php sim
Usuário da api cadastrado
Banco de dados apagado com sucesso.
Dados de controle inseridos/atualizados com sucesso

Mas aplicação ainda não roda.

**Comment by igorvc** [comment]
Executei o salvarAdmin.php nusp para criar admin...

**Comment by masakik** [comment]
Ola @igorvc, realmente o setup inicial precisa de algumas etapas que não documentei ainda.
Vou mexer nisso para segunda.
Sorry.

**Comment by masakik** [comment]
obrigado @igorvc a ajudar a encontrar o bug :cat2:
